name: 'rl-course-dev'
channels:
  - conda-forge
  - defaults
dependencies:
  - grpcio
  - ipykernel
  - ipywidgets
  - matplotlib
  - graphviz
  - pip
  - python=3.9
  - pip:
    - gputil
    - gym==0.22.0
    # - "gym[atari]==0.22.0" "gym[accept-rom-license]" atari_py
    - pygame
    - "ray[rllib]==1.10"
    - torch
    - torchvision