name: 'rl-course-dev-2'
channels:
  - conda-forge
  - defaults
dependencies:
  - grpcio
  - ipykernel
  - ipywidgets
  - matplotlib
  - graphviz
  - pip
  - python=3.8
  - pip:
    - dm_tree
    - gputil
    - gym[mujoco]
    # - gym==0.22.0
    # - "gym[atari]==0.22.0" "gym[accept-rom-license]" atari_py
    - pygame
    - "ray[rllib]==1.11.0"
    - torch
    - torchvision
  # note to self: if the grpcio thing doesn't work, use conda install --force