version: '3.7'
services:
  gatsby:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
     - .:/app
     - /app/node_modules/
